version: '3.5'

services:
  app:
    build: .
    restart: always
    environment:
      - DB_HOST=${DB_HOST:-exercise_db}
      - DB_USER=${DB_USER:-exercise}
      - DB_PW=${DB_PW:-exercise}
      - DB_NAME=${DB_NAME:-exercise}
      - API_PORT=${API_PORT:-5000}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-exercise_rabbitmq}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PW=${RABBITMQ_PW:-guest}
    container_name: exercise_api
    depends_on:
      - db
      - rabbitmq
    ports:
      - '5000:5000'
    networks:
      - db
      - rabbitmq

  db:
    container_name: exercise_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-exercise}
      - POSTGRES_PASSWORD=${DB_PW:-exercise}      
      - POSTGRES_DB=${DB_NAME:-exercise}
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data/:/data/db
    ports:
      - '5432:5432'
  
  rabbitmq:
    container_name: exercise_rabbitmq
    image: rabbitmq:3.11-management
    networks:
      - rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge
  rabbitmq:
    driver: bridge
