version: '3.5'

services:
  app:
    build:
      dockerfile: Dockerfile.test
      context: .
    container_name: feedbackapi_test
    depends_on:
      - db
    # Remove port forwarding and add the app to your reverse proxy network
    # before deploying
    ports:
      - '5000:5000'
    networks:
      - db

  db:
    container_name: feedback-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}      
      - POSTGRES_DB=${DB_NAME}
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data/:/data/db

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge
