apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jodel-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  superuserSecret:
    name: jodel-db-secret