apiVersion: apps/v1
kind: Deployment
metadata:
  name: jodel-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jodel
      tier: ui
  template:
    metadata:
      labels:
        app: jodel
        tier: ui
    spec:
      containers:
        - name: jodel-ui
          image: jodel-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 250m
      restartPolicy: Always
