version: '3.5'

services:
  app:
    container_name: jodel_app
    build: .
    restart: always
    environment:
      - JODEL_DB_RW_SERVICE_HOST=${DB_HOST:-jodel_db}
      - DB_USER=${DB_USER:-jodel}
      - DB_PW=${DB_PW:-jodel}
      - DB_NAME=${DB_NAME:-jodel}
      - API_PORT=${API_PORT:-5000}
    depends_on:
      - db
    ports:
      - '5000:5000'
    networks:
      - db

  db:
    container_name: jodel_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-jodel}
      - POSTGRES_PASSWORD=${DB_PW:-jodel}      
      - POSTGRES_DB=${DB_NAME:-jodel}
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data/:/data/db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-jodel}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge

