apiVersion: v1
kind: Service
metadata:
  name: jodel-app
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31236
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: jodel-app
  sessionAffinity: None
  type: LoadBalancer
