apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jodel-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  superuserSecret:
    name: jodel-db-secret
  # postgresql:
    # pg_hba:
    #   - host jodel jodel all md5
  # bootstrap:
  #   initdb:
  #     database: jodel
  #     owner: jodel
  #     secret:
  #       name: jodel-db-secret