version: '3.5'

services:
  api:
    build: .
    restart: always
    environment:
      - DB_HOST=${DB_HOST:-exercise_db}
      - DB_USER=${DB_USER:-exercise}
      - DB_PW=${DB_PW:-exercise}
      - DB_NAME=${DB_NAME:-exercise}
      - API_PORT=${API_PORT:-5000}
      - GRADER_PORT=${GRADER_PORT:-9001}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-exercise_rabbitmq}
      - RABBITMQ_USER=${RABBITMQ_USER:-exercise}
      - RABBITMQ_PW=${RABBITMQ_PW:-exercise}
    container_name: exercise_api
    depends_on:
      - grader
    ports:
      - '5000:5000'
    networks:
      - db
      - rabbitmq
      - grading

  grader:
    build: ./grader
    restart: always
    privileged: true
    environment:
      - DB_HOST=${DB_HOST:-exercise_db}
      - DB_USER=${DB_USER:-exercise}
      - DB_PW=${DB_PW:-exercise}
      - DB_NAME=${DB_NAME:-exercise}
      - API_PORT=${API_PORT:-5000}
      - GRADER_PORT=${GRADER_PORT:-9001}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-exercise_rabbitmq}
      - RABBITMQ_USER=${RABBITMQ_USER:-exercise}
      - RABBITMQ_PW=${RABBITMQ_PW:-exercise}
    container_name: exercise_grader
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '9001:9001'
    networks:
      - db
      - rabbitmq
      - grading

  rabbitmq:
    container_name: exercise_rabbitmq
    build: ./rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-exercise}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PW:-exercise}
    networks:
      - rabbitmq
    ports:
      - '15672:15672'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: exercise_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-exercise}
      - POSTGRES_PASSWORD=${DB_PW:-exercise}      
      - POSTGRES_DB=${DB_NAME:-exercise}
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data/:/data/db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-exercise}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge
  rabbitmq:
    driver: bridge
  grading:
    driver: bridge

